# personal desccription
fname = input("Enter your first name :")
lname = input("Enter your last name :")
country = input("Enter your country of origin :")
job = input("Enter the nature of current Job :")
email = input("Enter your email adress :")
phone = input("Enter your phone number :")
city = input("Enter your current city :")
address = input("Enter your physical adress :")
#name = fname + lname
print("Name:",fname + " " + lname )
print("Country:",country)
print("Profession :",job)
print("Email:",email)
print("Phone:", phone)
print("city :", city)
print("Address :",address)
